title: M0e
author: Mohammed F. Al-Barbari
email: moe@grodriket.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hi there, I am Mohammed Fadhl Al-Barbari 18 y/o cyber security researcher , Web dev/tester, Mobile applications dev/tester, tools builder and Bugs hunter .
  Hacker since 2015
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 1
paginate_path: "/blog/page:num/"
comments: true

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: m4dm0e-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/m4dm0e
      icon: twitter-square
      color: green
    - url: https://moe.grodriket.com
      icon: itch-io
      color: red
    - url: https://github.com/m4dm0e
      icon: github-square
      color: purple

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: m4dm0e
